name: trace
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyterlab
  - notebook
  - ipykernel
  - numba
  - pip:
      - git+https://github.com/nura-j/ABSynth_dataset.git
      - transformers
      - torch
      - huggingface-hub
      - hf-xet
      - tqdm