name: trace
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyterlab
  - notebook
  - ipykernel
  - numba
  - pip:
      - absynth==0.1.1
      - trace==0.1
      - transformers
      - torch
      - huggingface-hub
      - hf-xet
      - tqdm
